openapi: 3.0.1
info:
  title: shamrock-customer-booking-references-service
  version: "1.0"
paths:
  /internal/auth/key:
    get:
      operationId: newKey
      parameters:
      - name: principal
        in: query
        schema:
          type: string
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
  /internal/caches/invalidate-all:
    get:
      operationId: invalidateAll
      parameters:
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
  /v1/accounts/{account_id}/references/fields/{field}:
    get:
      operationId: getReferenceValues
      parameters:
      - name: account_id
        in: path
        required: true
        schema:
          pattern: "[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\\
            -[0-9a-fA-F]{12}"
          type: string
          format: uuid
      - name: field
        in: path
        required: true
        schema:
          type: string
      - name: related_to
        in: query
        schema:
          type: string
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReferenceValuesResponse'
  /v1/accounts/{account_id}/references/verify:
    post:
      operationId: verifyReferences
      parameters:
      - name: account_id
        in: path
        required: true
        schema:
          pattern: "[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\\
            -[0-9a-fA-F]{12}"
          type: string
          format: uuid
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerificationRequest'
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "201":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationResponse'
  /v1/clients/{client_id}/references/fields/{field}:
    get:
      operationId: getReferenceValues_1
      parameters:
      - name: client_id
        in: path
        required: true
        schema:
          pattern: "[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\\
            -[0-9a-fA-F]{12}"
          type: string
          format: uuid
      - name: field
        in: path
        required: true
        schema:
          type: string
      - name: related_to
        in: query
        schema:
          type: string
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReferenceValuesResponse'
  /v1/clients/{client_id}/references/verify:
    post:
      operationId: verifyReferences_1
      parameters:
      - name: client_id
        in: path
        required: true
        schema:
          pattern: "[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\\
            -[0-9a-fA-F]{12}"
          type: string
          format: uuid
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerificationRequest'
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "201":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationResponse'
  /v1/accounts/{account_id}/reference-schema:
    get:
      operationId: getReferences
      parameters:
      - name: account_id
        in: path
        required: true
        schema:
          pattern: "[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\\
            -[0-9a-fA-F]{12}"
          type: string
          format: uuid
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReferenceSchemaResponse'
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    Response:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        validation_errors:
          $ref: '#/components/schemas/ValidationErrors'
    ValidationErrors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    FieldValue:
      type: object
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
        name:
          type: string
        related_to:
          type: string
        tooltip:
          type: string
    ReferenceValuesResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        validation_errors:
          $ref: '#/components/schemas/ValidationErrors'
        values:
          type: array
          items:
            $ref: '#/components/schemas/FieldValue'
    VerificationError:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    VerificationResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        validation_errors:
          $ref: '#/components/schemas/ValidationErrors'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/VerificationError'
    CompanyReference:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
    VerificationRequest:
      type: object
      properties:
        company_references:
          type: array
          items:
            $ref: '#/components/schemas/CompanyReference'
    Field:
      type: object
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
        required:
          type: boolean
        depends_on:
          type: string
        type:
          type: string
        pattern:
          type: string
        list:
          type: boolean
        autocomplete:
          type: boolean
        placeholder:
          type: string
        tooltip:
          type: string
    ReferenceSchema:
      type: object
      properties:
        used:
          type: boolean
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
        required_groups:
          type: array
          items:
            $ref: '#/components/schemas/RequiredGroup'
    ReferenceSchemaResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        validation_errors:
          $ref: '#/components/schemas/ValidationErrors'
        reference_schema:
          $ref: '#/components/schemas/ReferenceSchema'
    RequiredGroup:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
