openapi: 3.0.1
info:
  title: shamrock-client-registry-service
  version: "1.0"
paths:
  /internal/auth/key:
    get:
      operationId: newKey
      parameters:
      - name: principal
        in: query
        schema:
          type: string
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
  /v1/accounts/{account_id}/clients/auth:
    post:
      operationId: auth
      parameters:
      - name: account_id
        in: path
        required: true
        schema:
          pattern: "[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\\
            -[0-9a-fA-F]{12}"
          type: string
          format: uuid
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientAuthRequest_Standard'
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "201":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientAuthResponse_Standard'
  /v1/accounts/{code}/clients/auth-schema:
    get:
      operationId: getAuthSchemaByCode
      parameters:
      - name: code
        in: path
        required: true
        schema:
          pattern: \d*
          type: string
      - name: booking_channel
        in: query
        schema:
          type: string
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientAuthSchemaResponse'
  /v1/accounts/{account_id}/clients/auth-schema:
    get:
      operationId: getAuthSchemaById
      parameters:
      - name: account_id
        in: path
        required: true
        schema:
          pattern: "[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\\
            -[0-9a-fA-F]{12}"
          type: string
          format: uuid
      - name: booking_channel
        in: query
        schema:
          type: string
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientAuthSchemaResponse'
  /v1/clients/{client_id}:
    get:
      operationId: getClient
      parameters:
      - name: client_id
        in: path
        required: true
        schema:
          pattern: "[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\\
            -[0-9a-fA-F]{12}"
          type: string
          format: uuid
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse_Standard'
  /v1/accounts/{account_id}/clients/search:
    get:
      operationId: search
      parameters:
      - name: account_id
        in: path
        required: true
        schema:
          pattern: "[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\\
            -[0-9a-fA-F]{12}"
          type: string
          format: uuid
      - name: name
        in: query
        schema:
          type: string
      - name: email
        in: query
        schema:
          type: string
      - name: telephone
        in: query
        schema:
          type: string
      - name: status
        in: query
        schema:
          type: string
      - name: X-Request-ID
        in: header
        description: Correlation ID attached to the request
        required: false
        schema:
          type: string
      - name: X-Service-Name
        in: header
        description: Name of the service/application component making the request
        required: false
        schema:
          type: string
      responses:
        default:
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: default response
          headers:
            X-Request-ID:
              description: Correlation id
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientsResponse_Extended'
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    Response:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        validation_errors:
          $ref: '#/components/schemas/ValidationErrors'
    ValidationErrors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    ClientAuthResponse_Standard:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        validation_errors:
          $ref: '#/components/schemas/ValidationErrors_Standard'
        authenticated:
          type: boolean
        customer_reference:
          $ref: '#/components/schemas/CustomerReference_Standard'
    Client_Standard:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        telephone:
          type: string
        email:
          type: string
    CustomerReference_Standard:
      type: object
      properties:
        pin_id:
          type: string
          format: uuid
        account_id:
          type: string
          format: uuid
        client:
          $ref: '#/components/schemas/Client_Standard'
    Error_Standard:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    ValidationErrors_Standard:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error_Standard'
    AccountName_Standard:
      type: object
      allOf:
      - $ref: '#/components/schemas/ClientAuth_Standard'
      - type: object
        properties:
          account_name:
            type: string
    AccountPassword_Standard:
      type: object
      allOf:
      - $ref: '#/components/schemas/ClientAuth_Standard'
      - type: object
        properties:
          account_password:
            type: string
    ClientAuthRequest_Standard:
      type: object
      properties:
        authentication:
          $ref: '#/components/schemas/ClientAuth_Standard'
        client:
          $ref: '#/components/schemas/ClientContext_Standard'
    ClientAuth_Standard:
      required:
      - '@type'
      type: object
      properties:
        '@type':
          type: string
      discriminator:
        propertyName: '@type'
    ClientContext_Standard:
      type: object
      properties:
        name:
          type: string
        telephone:
          type: string
        email:
          type: string
    Pin_Standard:
      type: object
      allOf:
      - $ref: '#/components/schemas/ClientAuth_Standard'
      - type: object
        properties:
          pin:
            type: string
    AccountName:
      type: object
      allOf:
      - $ref: '#/components/schemas/ClientAuthSchema'
    AccountPassword:
      type: object
      allOf:
      - $ref: '#/components/schemas/ClientAuthSchema'
    ClientAuthSchema:
      required:
      - '@type'
      type: object
      properties:
        '@type':
          type: string
      discriminator:
        propertyName: '@type'
    ClientAuthSchemaResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        account_id:
          type: string
          format: uuid
        authentication_schema:
          $ref: '#/components/schemas/ClientAuthSchema'
        validation_errors:
          $ref: '#/components/schemas/ValidationErrors'
    Pin:
      type: object
      allOf:
      - $ref: '#/components/schemas/ClientAuthSchema'
      - type: object
        properties:
          pin_alias:
            type: string
    ClientResponse_Standard:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        validation_errors:
          $ref: '#/components/schemas/ValidationErrors_Standard'
        account_id:
          type: string
          format: uuid
        client:
          $ref: '#/components/schemas/Client_Standard'
    Client_Extended:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        telephone:
          type: string
        email:
          type: string
        status:
          type: string
          enum:
          - ACTIVE
          - ON_HOLD
    ClientsResponse_Extended:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        validation_errors:
          $ref: '#/components/schemas/ValidationErrors_Extended'
        clients:
          type: array
          items:
            $ref: '#/components/schemas/Client_Extended'
    Error_Extended:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    ValidationErrors_Extended:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error_Extended'
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
